management.endpoints.web.exposure.include: health,info
# Resilience4j
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 1
      minimumNumberOfCalls: 1
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      slidingWindowType: TIME_BASED
      failureRateThreshold: 50
      waitDurationInOpenState: 500
      recordExceptions:
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpServerErrorException
        - java.lang.RuntimeException
  backends:
    nameService:
      baseConfig: default
# Dekorate
dekorate:
  kubernetes:
    env-vars:
      - name: NAME_HOST
        value: http://spring-boot-circuit-breaker-name:80
