name: "Push Images"
on:
  workflow_dispatch:
  push:
    branches:
      - sb-2.7.x
jobs:
  push:
    name: Push Images to Quay.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Quay.io Login
        run: docker login quay.io -u="${{secrets.QUAY_USER}}" -p="${{secrets.QUAY_TOKEN}}"
      - name: Build
        run: ./mvnw -s .github/mvn-settings.xml clean package
      - name: Push Image to Quay.io
        run: |
          CONTAINER_REGISTRY=quay.io/snowdrop
          ## Cute name service:
          NAME_IMAGE=spring-boot-cb-name-example:2.7
          docker build ./name-service -t $NAME_IMAGE
          docker tag $NAME_IMAGE $CONTAINER_REGISTRY/$NAME_IMAGE
          docker push $CONTAINER_REGISTRY/$NAME_IMAGE

          ## Greeting service:
          GREETING_IMAGE=spring-boot-cb-greeting-example:2.7
          docker build ./greeting-service -t $GREETING_IMAGE
          docker tag $GREETING_IMAGE $CONTAINER_REGISTRY/$GREETING_IMAGE
          docker push $CONTAINER_REGISTRY/$GREETING_IMAGE
